/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.test.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the Entry service. Represents a row in the &quot;Event_Entry&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.test.model.impl.EntryModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.test.model.impl.EntryImpl}.
 * </p>
 *
 * @author asanchez
 * @see Entry
 * @see com.test.model.impl.EntryImpl
 * @see com.test.model.impl.EntryModelImpl
 * @generated
 */
public interface EntryModel extends BaseModel<Entry> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a entry model instance should use the {@link Entry} interface instead.
	 */

	/**
	 * Returns the primary key of this entry.
	 *
	 * @return the primary key of this entry
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this entry.
	 *
	 * @param primaryKey the primary key of this entry
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the tm_ ID of this entry.
	 *
	 * @return the tm_ ID of this entry
	 */
	public long getTm_Id();

	/**
	 * Sets the tm_ ID of this entry.
	 *
	 * @param tm_Id the tm_ ID of this entry
	 */
	public void setTm_Id(long tm_Id);

	/**
	 * Returns the user of this entry.
	 *
	 * @return the user of this entry
	 */
	@AutoEscape
	public String getUser();

	/**
	 * Sets the user of this entry.
	 *
	 * @param user the user of this entry
	 */
	public void setUser(String user);

	/**
	 * Returns the message of this entry.
	 *
	 * @return the message of this entry
	 */
	@AutoEscape
	public String getMessage();

	/**
	 * Sets the message of this entry.
	 *
	 * @param message the message of this entry
	 */
	public void setMessage(String message);

	/**
	 * Returns the date of this entry.
	 *
	 * @return the date of this entry
	 */
	@AutoEscape
	public String getDate();

	/**
	 * Sets the date of this entry.
	 *
	 * @param date the date of this entry
	 */
	public void setDate(String date);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(com.test.model.Entry entry);

	@Override
	public int hashCode();

	@Override
	public CacheModel<com.test.model.Entry> toCacheModel();

	@Override
	public com.test.model.Entry toEscapedModel();

	@Override
	public com.test.model.Entry toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}